#!/usr/bin/env python3
"""Build OpenBST (BeSTspeech) as a dual-slice XCFramework for iOS.

Cross-compiles the upstream C sources for both the device and the simulator,
archives each slice, and asks xcodebuild to assemble the XCFramework so the
embedded Info.plist is generated by the tool rather than hand-maintained.

Usage:
    python3 build_frameworks.py [--upstream /path/to/openbst] [--no-tables]

--no-tables builds the engine without any of the lifted tables, which is what a
public build ships: the tables are the part that belongs to someone else, and the
user supplies them at run time instead. The engine code is untouched either way --
the table modules are simply left out and iOSProject/Engine/no-tables.c stands in
for the index that looks them up. That is what makes `bst_open(build)` fail and
`bst_open_image(build, ...)` work, which is the whole arrangement.

Test suites build the tables-in archive; only shipping uses --no-tables.
"""

import argparse
import concurrent.futures
import glob
import os
import shutil
import subprocess
import sys

DEFAULT_UPSTREAM = os.path.expanduser("~/openbst")
HERE = os.path.dirname(os.path.abspath(__file__))
OUTPUT_NAME = "OpenBST.xcframework"
BUILD_ROOT = os.path.join(HERE, "..", "build_frameworks")

SLICES = {
    # name    clang -target                    sdk
    "device": ["arm64-apple-ios17.0"],          # iphoneos
    "sim": ["arm64-apple-ios17.0-simulator",    # iphonesimulator
            "x86_64-apple-ios17.0-simulator"],
}

SDK_FOR = {
    "device": "iphoneos",
    "sim": "iphonesimulator",
}

CFLAGS = ["-O2", "-g", "-Wall", "-Wextra", "-std=gnu11", "-fPIC"]

# The generated table index, one file per build. A build without tables must not
# compile any of them, or the archive is not table-free and the module would be
# duplicated besides.
TABLE_DIR = os.path.join("src", "data")


def sdk_path(sdk):
    return subprocess.check_output(
        ["xcrun", "--sdk", sdk, "--show-sdk-path"], text=True
    ).strip()


def sources_for(upstream, with_tables):
    """Every C source to compile, minus the tables when they are excluded."""
    sources = sorted(glob.glob(os.path.join(upstream, "src", "**", "*.c"), recursive=True))
    if not with_tables:
        table_dir = os.path.join(upstream, TABLE_DIR) + os.sep
        sources = [s for s in sources if not s.startswith(table_dir)]
        # The stub that stands in for bst_lifted_for, so the library still links
        # and still enumerates the build names.
        stub = os.path.join(HERE, "Engine", "no-tables.c")
        if not os.path.isfile(stub):
            sys.exit(f"table-free build needs {stub}")
        sources.append(stub)
    if not sources:
        sys.exit(f"No C sources found under {upstream}/src")
    return sources


def compile_one(args):
    src, obj, target, sdk, include = args
    cmd = [
        "clang",
        "-target", target,
        "-isysroot", sdk,
        *CFLAGS,
        f"-I{include}",
        "-c", src,
        "-o", obj,
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        return src, proc.stderr
    return src, None


def build_slice(name, upstream, jobs, with_tables, build_root):
    targets = SLICES[name]
    sdk = sdk_path(SDK_FOR[name])
    include = os.path.join(upstream, "include")

    out_dir = os.path.join(build_root, name)
    shutil.rmtree(out_dir, ignore_errors=True)
    os.makedirs(out_dir, exist_ok=True)

    sources = sources_for(upstream, with_tables)
    print(f"[{name}] compiling {len(sources)} files for {len(targets)} arch(s)"
          f"{'' if with_tables else ' (no tables)'}")

    work = []
    for arch_i, target in enumerate(targets):
        arch_dir = os.path.join(out_dir, f"arch{arch_i}")
        os.makedirs(arch_dir, exist_ok=True)
        for src in sources:
            rel = os.path.relpath(src, upstream).replace(os.sep, "_").replace(".c", ".o")
            if os.path.isabs(rel) or rel.startswith(".."):
                # The no-tables stub lives outside the upstream tree.
                rel = "stub_" + os.path.basename(src).replace(".c", ".o")
            work.append((src, os.path.join(arch_dir, rel), target, sdk, include))

    failures = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=jobs) as pool:
        for src, err in pool.map(compile_one, work):
            if err:
                failures.append((src, err))

    if failures:
        for src, err in failures[:5]:
            print(f"[{name}] FAILED {src}\n{err}", file=sys.stderr)
        sys.exit(f"[{name}] {len(failures)} file(s) failed to compile")

    # One archive per architecture, then lipo them into a single fat slice.
    per_arch = []
    for arch_i in range(len(targets)):
        arch_dir = os.path.join(out_dir, f"arch{arch_i}")
        objects = sorted(glob.glob(os.path.join(arch_dir, "*.o")))
        thin = os.path.join(out_dir, f"thin{arch_i}.a")
        if os.path.exists(thin):
            os.remove(thin)
        subprocess.run(["ar", "rcs", thin, *objects], check=True)
        per_arch.append(thin)

    lib = os.path.join(build_root, f"libbst_{name}.a")
    if os.path.exists(lib):
        os.remove(lib)
    if len(per_arch) == 1:
        shutil.copyfile(per_arch[0], lib)
    else:
        subprocess.run(["lipo", "-create", "-output", lib, *per_arch], check=True)
    print(f"[{name}] wrote {lib} ({' + '.join(targets)})")
    return lib


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", default=DEFAULT_UPSTREAM,
                    help="path to the upstream openbst checkout")
    ap.add_argument("--jobs", type=int, default=os.cpu_count() or 4)
    ap.add_argument("--no-tables", action="store_true",
                    help="build without the lifted tables, as a public build does")
    opts = ap.parse_args()

    upstream = os.path.abspath(os.path.expanduser(opts.upstream))
    if not os.path.isdir(os.path.join(upstream, "src")):
        sys.exit(f"Not an openbst checkout: {upstream}")

    headers = os.path.join(upstream, "include")
    if not os.path.isfile(os.path.join(headers, "bst.h")):
        sys.exit(f"bst.h not found in {headers}")

    with_tables = not opts.no_tables
    build_root = BUILD_ROOT if with_tables else BUILD_ROOT + "-notables"

    libs = {name: build_slice(name, upstream, opts.jobs, with_tables, build_root)
            for name in SLICES}

    output = os.path.join(HERE, "Frameworks",
                          OUTPUT_NAME if with_tables else "OpenBSTNoTables.xcframework")
    shutil.rmtree(output, ignore_errors=True)
    os.makedirs(os.path.dirname(output), exist_ok=True)
    subprocess.run(
        [
            "xcodebuild", "-create-xcframework",
            "-library", libs["device"], "-headers", headers,
            "-library", libs["sim"], "-headers", headers,
            "-output", output,
        ],
        check=True,
    )
    print(f"wrote {output} ({'with' if with_tables else 'without'} tables)")


if __name__ == "__main__":
    main()
