#!/usr/bin/env python3
"""Build OpenBST (BeSTspeech) as a dual-slice XCFramework for iOS.

Cross-compiles the upstream C sources for both the device and the simulator,
archives each slice, and asks xcodebuild to assemble the XCFramework so the
embedded Info.plist is generated by the tool rather than hand-maintained.

Usage:
    python3 build_frameworks.py [--upstream /path/to/openbst]
"""

import argparse
import concurrent.futures
import glob
import os
import shutil
import subprocess
import sys

DEFAULT_UPSTREAM = os.path.expanduser("~/openbst")
HERE = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(HERE, "Frameworks", "OpenBST.xcframework")
BUILD_ROOT = os.path.join(HERE, "..", "build_frameworks")

SLICES = {
    # name    clang -target                    sdk
    "device": ["arm64-apple-ios17.0"],          # iphoneos
    "sim": ["arm64-apple-ios17.0-simulator",    # iphonesimulator
            "x86_64-apple-ios17.0-simulator"],
}

SDK_FOR = {
    "device": "iphoneos",
    "sim": "iphonesimulator",
}

CFLAGS = ["-O2", "-g", "-Wall", "-Wextra", "-std=gnu11", "-fPIC"]


def sdk_path(sdk):
    return subprocess.check_output(
        ["xcrun", "--sdk", sdk, "--show-sdk-path"], text=True
    ).strip()


def compile_one(args):
    src, obj, target, sdk, include = args
    cmd = [
        "clang",
        "-target", target,
        "-isysroot", sdk,
        *CFLAGS,
        f"-I{include}",
        "-c", src,
        "-o", obj,
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        return src, proc.stderr
    return src, None


def build_slice(name, upstream, jobs):
    targets = SLICES[name]
    sdk = sdk_path(SDK_FOR[name])
    include = os.path.join(upstream, "include")

    out_dir = os.path.join(BUILD_ROOT, name)
    shutil.rmtree(out_dir, ignore_errors=True)
    os.makedirs(out_dir, exist_ok=True)

    sources = sorted(glob.glob(os.path.join(upstream, "src", "**", "*.c"), recursive=True))
    if not sources:
        sys.exit(f"No C sources found under {upstream}/src")

    print(f"[{name}] compiling {len(sources)} files for {len(targets)} arch(s)")

    work = []
    for arch_i, target in enumerate(targets):
        arch_dir = os.path.join(out_dir, f"arch{arch_i}")
        os.makedirs(arch_dir, exist_ok=True)
        for src in sources:
            rel = os.path.relpath(src, upstream).replace(os.sep, "_").replace(".c", ".o")
            work.append((src, os.path.join(arch_dir, rel), target, sdk, include))

    failures = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=jobs) as pool:
        for src, err in pool.map(compile_one, work):
            if err:
                failures.append((src, err))

    if failures:
        for src, err in failures[:5]:
            print(f"[{name}] FAILED {src}\n{err}", file=sys.stderr)
        sys.exit(f"[{name}] {len(failures)} file(s) failed to compile")

    # One archive per architecture, then lipo them into a single fat slice.
    per_arch = []
    for arch_i in range(len(targets)):
        arch_dir = os.path.join(out_dir, f"arch{arch_i}")
        objects = sorted(glob.glob(os.path.join(arch_dir, "*.o")))
        thin = os.path.join(out_dir, f"thin{arch_i}.a")
        if os.path.exists(thin):
            os.remove(thin)
        subprocess.run(["ar", "rcs", thin, *objects], check=True)
        per_arch.append(thin)

    lib = os.path.join(BUILD_ROOT, f"libbst_{name}.a")
    if os.path.exists(lib):
        os.remove(lib)
    if len(per_arch) == 1:
        shutil.copyfile(per_arch[0], lib)
    else:
        subprocess.run(["lipo", "-create", "-output", lib, *per_arch], check=True)
    print(f"[{name}] wrote {lib} ({' + '.join(targets)})")
    return lib


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--upstream", default=DEFAULT_UPSTREAM,
                    help="path to the upstream openbst checkout")
    ap.add_argument("--jobs", type=int, default=os.cpu_count() or 4)
    opts = ap.parse_args()

    upstream = os.path.abspath(os.path.expanduser(opts.upstream))
    if not os.path.isdir(os.path.join(upstream, "src")):
        sys.exit(f"Not an openbst checkout: {upstream}")

    headers = os.path.join(upstream, "include")
    if not os.path.isfile(os.path.join(headers, "bst.h")):
        sys.exit(f"bst.h not found in {headers}")

    libs = {name: build_slice(name, upstream, opts.jobs) for name in SLICES}

    shutil.rmtree(OUTPUT, ignore_errors=True)
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    subprocess.run(
        [
            "xcodebuild", "-create-xcframework",
            "-library", libs["device"], "-headers", headers,
            "-library", libs["sim"], "-headers", headers,
            "-output", OUTPUT,
        ],
        check=True,
    )
    print(f"XCFramework written to {OUTPUT}")


if __name__ == "__main__":
    main()
