#!/usr/bin/env python3
"""Generate plural forms for every symbol the app substitutes for a number.

Two CLDR sources, because the data lives in different places per kind:

- **units** (`cldr-units-full`) -- the degree sign and the other measure symbols.
- **currencies** (`cldr-numbers-full`) -- "5 euro" should be "5 euros"; CLDR's
  currency display names carry the same one/other forms.

CLDR keeps a character's NAME in its emoji annotations ("degree", singular) and
its PLURAL FORMS in these files, with no mapping between the two. `SYMBOLS` below
is the one link written down rather than derived.
"""
import json
import urllib.request
from pathlib import Path

LOCALES = ["en", "es", "fr", "de", "it", "nl", "pl", "pt",
           "ru", "ar", "ja", "he", "el"]

# Symbol (hex scalars, the CLDR table's key) -> which CLDR entry names it.
UNITS = {"B0": "angle-degree"}
CURRENCIES = {
    "A2": "cent",       # not an ISO code; handled below
    "A3": "GBP",
    "A5": "JPY",
    "20AC": "EUR",
    "20A9": "KRW",
    "20AA": "ILS",
    "20A6": "NGN",
    "20B1": "PHP",
    "20B4": "UAH",
    "20B9": "INR",
    "20BA": "TRY",
    "20BD": "RUB",
    "E3F": "THB",
    "A4": "generic",    # the generic currency sign
}

CACHE = Path.home() / "cldr-units"
UNITS_URL = ("https://raw.githubusercontent.com/unicode-org/cldr-json/main/"
             "cldr-json/cldr-units-full/main/%s/units.json")
CURR_URL = ("https://raw.githubusercontent.com/unicode-org/cldr-json/main/"
            "cldr-json/cldr-numbers-full/main/%s/currencies.json")
OUT = Path(__file__).resolve().parent.parent / "iOSProject/Shared/UnitPlurals.swift"


def fetch(url_tmpl, locale, tag):
    CACHE.mkdir(exist_ok=True)
    dest = CACHE / ("%s-%s.json" % (tag, locale))
    if not dest.exists():
        with urllib.request.urlopen(url_tmpl % locale, timeout=60) as r:
            dest.write_bytes(r.read())
    return json.loads(dest.read_text(encoding="utf-8"))


def sw(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def forms(pattern_source):
    """The count-* display names, without the {0} placeholder."""
    out = {}
    for key, value in pattern_source.items():
        if not key.startswith("displayName-count-"):
            continue
        name = value.strip()
        if name:
            out[key[len("displayName-count-"):]] = name
    return out


def main():
    table = {}          # locale -> symbolKey -> category -> name
    for locale in LOCALES:
        try:
            units = fetch(UNITS_URL, locale, "units")["main"][locale]["units"]["long"]
        except Exception:
            units = {}
        try:
            cur = (fetch(CURR_URL, locale, "currencies")
                   ["main"][locale]["numbers"]["currencies"])
        except Exception:
            cur = {}

        for symbol, unit in UNITS.items():
            entry = units.get(unit)
            if not entry:
                continue
            got = {}
            for key, value in entry.items():
                if not key.startswith("unitPattern-count-"):
                    continue
                name = value.replace("{0}", "").strip()
                if name:
                    got[key[len("unitPattern-count-"):]] = name
            if got:
                table.setdefault(locale, {})[symbol] = got

        for symbol, code in CURRENCIES.items():
            if code == "cent":
                # No ISO code for the cent; CLDR has no entry for it, and the
                # plural is simply "cent"/"cents" in English.
                if locale == "en":
                    table.setdefault(locale, {})[symbol] = {"one": "cent",
                                                            "other": "cents"}
                continue
            entry = cur.get(code)
            if not entry and symbol == "A4":
                continue
            if not entry:
                continue
            got = forms(entry)
            if got:
                table.setdefault(locale, {})[symbol] = got

    lines = [
        "// Generated by tools/build_units.py -- do not edit by hand.",
        "//",
        "// The plural forms CLDR gives for a symbol that stands in for a number's",
        '// unit, so "84 degree" reads as "84 degrees" and "5 euro" as "5 euros".',
        "// CLDR keeps a character's NAME in its emoji annotations, singular, and",
        "// these PLURAL FORMS in its units and currency data, with no mapping",
        "// between the two -- `symbolUnits` below is the one link written down.",
        "",
        "import Foundation",
        "",
        "enum UnitPlurals {",
        "    /// Hex-scalar symbol -> CLDR plural category -> the name to say.",
        "    /// The category comes from `SSMLText.pluralCategory(of:language:)`,",
        "    /// which is CLDR's own cardinal rule for the language rather than an",
        "    /// English `count == 1` test.",
        "    static let names: [String: [String: [String: String]]] = [",
    ]
    for locale in sorted(table):
        inner = []
        for symbol in sorted(table[locale]):
            pairs = ", ".join("%s: %s" % (sw(k), sw(v))
                              for k, v in sorted(table[locale][symbol].items()))
            inner.append("%s: [%s]" % (sw(symbol), pairs))
        lines.append("        %s: [%s]," % (sw(locale), ", ".join(inner)))
    lines += ["    ]", "}", ""]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("  wrote %s (%d bytes)" % (OUT.name, OUT.stat().st_size))
    print("  locales: %d" % len(table))
    for locale in sorted(table):
        print("     %-3s %s" % (locale, "  ".join(
            "%s=%s" % (s, "/".join(table[locale][s][k] for k in sorted(table[locale][s])))
            for s in sorted(table[locale]))))


main()
